//go:build darwin

package key

import "runtime"

// macOS virtual key codes (CGKeyCode / NSEvent.keyCode from Carbon HIToolbox Events.h)
var (
	Backspace      Key = Key{0x33, "Backspace", runtime.GOOS}   // kVK_Delete (backspace key)
	Tab            Key = Key{0x30, "Tab", runtime.GOOS}
	Enter          Key = Key{0x24, "Enter", runtime.GOOS}      // kVK_Return
	Escape         Key = Key{0x35, "Escape", runtime.GOOS}
	Space          Key = Key{0x31, "Space", runtime.GOOS}
	PageUp         Key = Key{0x74, "PageUp", runtime.GOOS}
	PageDown       Key = Key{0x79, "PageDown", runtime.GOOS}
	End            Key = Key{0x77, "End", runtime.GOOS}
	Home           Key = Key{0x73, "Home", runtime.GOOS}
	Left           Key = Key{0x7B, "Left", runtime.GOOS}
	Up             Key = Key{0x7E, "Up", runtime.GOOS}
	Right          Key = Key{0x7C, "Right", runtime.GOOS}
	Down           Key = Key{0x7D, "Down", runtime.GOOS}
	Insert         Key = Key{0x72, "Insert", runtime.GOOS}     // kVK_Help (often mapped to Insert on extended keyboards)
	Delete         Key = Key{0x75, "Delete", runtime.GOOS}     // kVK_ForwardDelete
	Number0        Key = Key{0x1D, "0", runtime.GOOS}
	Number1        Key = Key{0x12, "1", runtime.GOOS}
	Number2        Key = Key{0x13, "2", runtime.GOOS}
	Number3        Key = Key{0x14, "3", runtime.GOOS}
	Number4        Key = Key{0x15, "4", runtime.GOOS}
	Number5        Key = Key{0x17, "5", runtime.GOOS}
	Number6        Key = Key{0x16, "6", runtime.GOOS}
	Number7        Key = Key{0x1A, "7", runtime.GOOS}
	Number8        Key = Key{0x1C, "8", runtime.GOOS}
	Number9        Key = Key{0x19, "9", runtime.GOOS}
	A              Key = Key{0x00, "A", runtime.GOOS}
	B              Key = Key{0x0B, "B", runtime.GOOS}
	C              Key = Key{0x08, "C", runtime.GOOS}
	D              Key = Key{0x02, "D", runtime.GOOS}
	E              Key = Key{0x0E, "E", runtime.GOOS}
	F              Key = Key{0x03, "F", runtime.GOOS}
	G              Key = Key{0x05, "G", runtime.GOOS}
	H              Key = Key{0x04, "H", runtime.GOOS}
	I              Key = Key{0x22, "I", runtime.GOOS}
	J              Key = Key{0x26, "J", runtime.GOOS}
	K              Key = Key{0x28, "K", runtime.GOOS}
	L              Key = Key{0x25, "L", runtime.GOOS}
	M              Key = Key{0x2E, "M", runtime.GOOS}
	N              Key = Key{0x2D, "N", runtime.GOOS}
	O              Key = Key{0x1F, "O", runtime.GOOS}
	P              Key = Key{0x23, "P", runtime.GOOS}
	Q              Key = Key{0x0C, "Q", runtime.GOOS}
	R              Key = Key{0x0F, "R", runtime.GOOS}
	S              Key = Key{0x01, "S", runtime.GOOS}
	T              Key = Key{0x11, "T", runtime.GOOS}
	U              Key = Key{0x20, "U", runtime.GOOS}
	V              Key = Key{0x09, "V", runtime.GOOS}
	W              Key = Key{0x0D, "W", runtime.GOOS}
	X              Key = Key{0x07, "X", runtime.GOOS}
	Y              Key = Key{0x10, "Y", runtime.GOOS}
	Z              Key = Key{0x06, "Z", runtime.GOOS}
	LeftWin        Key = Key{0x37, "LeftWin", runtime.GOOS}   // kVK_Command (Apple/Command)
	RightWin       Key = Key{0x36, "RightWin", runtime.GOOS}  // kVK_RightCommand
	NumPad0        Key = Key{0x52, "Num0", runtime.GOOS}
	NumPad1        Key = Key{0x53, "Num1", runtime.GOOS}
	NumPad2        Key = Key{0x54, "Num2", runtime.GOOS}
	NumPad3        Key = Key{0x55, "Num3", runtime.GOOS}
	NumPad4        Key = Key{0x56, "Num4", runtime.GOOS}
	NumPad5        Key = Key{0x57, "Num5", runtime.GOOS}
	NumPad6        Key = Key{0x58, "Num6", runtime.GOOS}
	NumPad7        Key = Key{0x59, "Num7", runtime.GOOS}
	NumPad8        Key = Key{0x5B, "Num8", runtime.GOOS}
	NumPad9        Key = Key{0x5C, "Num9", runtime.GOOS}
	NumPadMultiply Key = Key{0x43, "Num*", runtime.GOOS}
	NumPadAdd      Key = Key{0x45, "Num+", runtime.GOOS}
	NumPadSubtract Key = Key{0x4E, "Num-", runtime.GOOS}
	NumPadDecimal  Key = Key{0x41, "Num.", runtime.GOOS}
	NumPadDivide   Key = Key{0x4B, "Num/", runtime.GOOS}
	F1             Key = Key{0x7A, "F1", runtime.GOOS}
	F2             Key = Key{0x78, "F2", runtime.GOOS}
	F3             Key = Key{0x63, "F3", runtime.GOOS}
	F4             Key = Key{0x76, "F4", runtime.GOOS}
	F5             Key = Key{0x60, "F5", runtime.GOOS}
	F6             Key = Key{0x61, "F6", runtime.GOOS}
	F7             Key = Key{0x62, "F7", runtime.GOOS}
	F8             Key = Key{0x64, "F8", runtime.GOOS}
	F9             Key = Key{0x65, "F9", runtime.GOOS}
	F10            Key = Key{0x6D, "F10", runtime.GOOS}
	F11            Key = Key{0x67, "F11", runtime.GOOS}
	F12            Key = Key{0x6F, "F12", runtime.GOOS}
	F13            Key = Key{0x69, "F13", runtime.GOOS}
	F14            Key = Key{0x6B, "F14", runtime.GOOS}
	F15            Key = Key{0x71, "F15", runtime.GOOS}
	F16            Key = Key{0x6A, "F16", runtime.GOOS}
	F17            Key = Key{0x40, "F17", runtime.GOOS}
	F18            Key = Key{0x4F, "F18", runtime.GOOS}
	F19            Key = Key{0x50, "F19", runtime.GOOS}
	F20            Key = Key{0x5A, "F20", runtime.GOOS}
	F21            Key = Key{0x83, "F21", runtime.GOOS} // extended
	F22            Key = Key{0x84, "F22", runtime.GOOS}
	F23            Key = Key{0x85, "F23", runtime.GOOS}
	F24            Key = Key{0x86, "F24", runtime.GOOS}
	NumLock        Key = Key{0x47, "NumLock", runtime.GOOS}   // kVK_ANSI_KeypadClear
	ScrollLock     Key = Key{0x70, "ScrollLock", runtime.GOOS} // no direct equivalent; use 0x70
	PrintScreen    Key = Key{0x6E, "PrintScreen", runtime.GOOS} // F14 or similar; macOS has no PrintScreen
	Pause          Key = Key{0x7F, "Pause", runtime.GOOS}    // no direct equivalent
	LeftShift      Key = Key{0x38, "LeftShift", runtime.GOOS}
	RightShift     Key = Key{0x3C, "RightShift", runtime.GOOS}
	LeftControl    Key = Key{0x3B, "LeftControl", runtime.GOOS}
	RightControl   Key = Key{0x3E, "RightControl", runtime.GOOS}
	LeftAlt        Key = Key{0x3A, "LeftAlt", runtime.GOOS}   // kVK_Option
	RightAlt       Key = Key{0x3D, "RightAlt", runtime.GOOS}  // kVK_RightOption
	Backtick       Key = Key{0x32, "`", runtime.GOOS}         // kVK_ANSI_Grave
	LeftBracket    Key = Key{0x21, "[", runtime.GOOS}
	RightBracket   Key = Key{0x1E, "]", runtime.GOOS}
	Backslash      Key = Key{0x2A, "\\", runtime.GOOS}
	SemiColon      Key = Key{0x29, ";", runtime.GOOS}
	CapsLock       Key = Key{0x39, "CapsLock", runtime.GOOS}
	Plus           Key = Key{0x18, "+", runtime.GOOS}  // kVK_ANSI_Equal (unshifted =)
	Comma          Key = Key{0x2B, ",", runtime.GOOS}
	Minus          Key = Key{0x1B, "-", runtime.GOOS}
	Period         Key = Key{0x2F, ".", runtime.GOOS}
	Slash          Key = Key{0x2C, "/", runtime.GOOS}
	Quote          Key = Key{0x27, "'", runtime.GOOS}
)
