// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {rules} from '../models';
import {app} from '../models';

export function BrowseForExecutable():Promise<string>;

export function GetDefaultProfiles():Promise<rules.Profiles>;

export function GetInfoBannerDismissed():Promise<boolean>;

export function GetInstalledApplications():Promise<Array<rules.InstalledApplication>>;

export function GetNotifyOnMinimize():Promise<boolean>;

export function GetNotifyOnUpdate():Promise<boolean>;

export function GetStartHidden():Promise<boolean>;

export function GetStartPlayingOnLaunch():Promise<boolean>;

export function IsValidGlobPattern(arg1:string):Promise<boolean>;

export function ListRules():Promise<Array<app.RuleData>>;

export function RemoveRule(arg1:string):Promise<void>;

export function SetDefaultProfiles(arg1:any,arg2:any):Promise<void>;

export function SetInfoBannerDismissed(arg1:boolean):Promise<void>;

export function SetNotifyOnMinimize(arg1:boolean):Promise<void>;

export function SetNotifyOnUpdate(arg1:boolean):Promise<void>;

export function SetStartHidden(arg1:boolean):Promise<void>;

export function SetStartPlayingOnLaunch(arg1:boolean):Promise<void>;

export function ToggleRule(arg1:string):Promise<void>;

export function UpdateRuleProfiles(arg1:string,arg2:any,arg3:any):Promise<void>;

export function UpsertRule(arg1:string,arg2:any,arg3:any,arg4:boolean):Promise<void>;
