// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseForExecutable() {
  return window['go']['app']['AppRules']['BrowseForExecutable']();
}

export function GetDefaultProfiles() {
  return window['go']['app']['AppRules']['GetDefaultProfiles']();
}

export function GetInfoBannerDismissed() {
  return window['go']['app']['AppRules']['GetInfoBannerDismissed']();
}

export function GetInstalledApplications() {
  return window['go']['app']['AppRules']['GetInstalledApplications']();
}

export function GetNotifyOnMinimize() {
  return window['go']['app']['AppRules']['GetNotifyOnMinimize']();
}

export function GetNotifyOnUpdate() {
  return window['go']['app']['AppRules']['GetNotifyOnUpdate']();
}

export function GetStartHidden() {
  return window['go']['app']['AppRules']['GetStartHidden']();
}

export function GetStartPlayingOnLaunch() {
  return window['go']['app']['AppRules']['GetStartPlayingOnLaunch']();
}

export function IsValidGlobPattern(arg1) {
  return window['go']['app']['AppRules']['IsValidGlobPattern'](arg1);
}

export function ListRules() {
  return window['go']['app']['AppRules']['ListRules']();
}

export function RemoveRule(arg1) {
  return window['go']['app']['AppRules']['RemoveRule'](arg1);
}

export function SetDefaultProfiles(arg1, arg2) {
  return window['go']['app']['AppRules']['SetDefaultProfiles'](arg1, arg2);
}

export function SetInfoBannerDismissed(arg1) {
  return window['go']['app']['AppRules']['SetInfoBannerDismissed'](arg1);
}

export function SetNotifyOnMinimize(arg1) {
  return window['go']['app']['AppRules']['SetNotifyOnMinimize'](arg1);
}

export function SetNotifyOnUpdate(arg1) {
  return window['go']['app']['AppRules']['SetNotifyOnUpdate'](arg1);
}

export function SetStartHidden(arg1) {
  return window['go']['app']['AppRules']['SetStartHidden'](arg1);
}

export function SetStartPlayingOnLaunch(arg1) {
  return window['go']['app']['AppRules']['SetStartPlayingOnLaunch'](arg1);
}

export function ToggleRule(arg1) {
  return window['go']['app']['AppRules']['ToggleRule'](arg1);
}

export function UpdateRuleProfiles(arg1, arg2, arg3) {
  return window['go']['app']['AppRules']['UpdateRuleProfiles'](arg1, arg2, arg3);
}

export function UpsertRule(arg1, arg2, arg3, arg4) {
  return window['go']['app']['AppRules']['UpsertRule'](arg1, arg2, arg3, arg4);
}
