// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetState() {
  return window['go']['app']['AudioEffects']['GetState']();
}

export function SetKeyboardEqualizer(arg1, arg2) {
  return window['go']['app']['AudioEffects']['SetKeyboardEqualizer'](arg1, arg2);
}

export function SetKeyboardPan(arg1, arg2, arg3) {
  return window['go']['app']['AudioEffects']['SetKeyboardPan'](arg1, arg2, arg3);
}

export function SetKeyboardPitchShift(arg1, arg2, arg3) {
  return window['go']['app']['AudioEffects']['SetKeyboardPitchShift'](arg1, arg2, arg3);
}

export function SetMouseEqualizer(arg1, arg2) {
  return window['go']['app']['AudioEffects']['SetMouseEqualizer'](arg1, arg2);
}

export function SetMousePan(arg1) {
  return window['go']['app']['AudioEffects']['SetMousePan'](arg1);
}

export function SetMousePitchShift(arg1, arg2, arg3) {
  return window['go']['app']['AudioEffects']['SetMousePitchShift'](arg1, arg2, arg3);
}
