// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {audio} from '../models';

export function GetState():Promise<app.AudioEffectsState>;

export function SetKeyboardEqualizer(arg1:boolean,arg2:audio.EqualizerConfig):Promise<void>;

export function SetKeyboardPan(arg1:boolean,arg2:string,arg3:number):Promise<void>;

export function SetKeyboardPitchShift(arg1:boolean,arg2:number,arg3:number):Promise<void>;

export function SetMouseEqualizer(arg1:boolean,arg2:audio.EqualizerConfig):Promise<void>;

export function SetMousePan(arg1:boolean):Promise<void>;

export function SetMousePitchShift(arg1:boolean,arg2:number,arg3:number):Promise<void>;
