// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetForkCount():Promise<number>;

export function GetInviteURL():Promise<string>;

export function GetIssueCount():Promise<number>;

export function GetOnlineCount():Promise<number>;

export function GetStarCount():Promise<number>;

export function GetTotalCount():Promise<number>;
