// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInviteURL() {
  return window['go']['app']['CommunityBinding']['GetInviteURL']();
}

export function GetOnlineCount() {
  return window['go']['app']['CommunityBinding']['GetOnlineCount']();
}

export function GetTotalCount() {
  return window['go']['app']['CommunityBinding']['GetTotalCount']();
}
