// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetForkCount() {
  return window['go']['app']['CommunityBinding']['GetForkCount']();
}

export function GetInviteURL() {
  return window['go']['app']['CommunityBinding']['GetInviteURL']();
}

export function GetIssueCount() {
  return window['go']['app']['CommunityBinding']['GetIssueCount']();
}

export function GetOnlineCount() {
  return window['go']['app']['CommunityBinding']['GetOnlineCount']();
}

export function GetStarCount() {
  return window['go']['app']['CommunityBinding']['GetStarCount']();
}

export function GetTotalCount() {
  return window['go']['app']['CommunityBinding']['GetTotalCount']();
}
