// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hotkeys} from '../models';

export function GetHotKeys():Promise<hotkeys.HotKeys>;

export function SetHotKeys(arg1:hotkeys.HotKeys):Promise<void>;
