// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHotKeys() {
  return window['go']['app']['HotKeys']['GetHotKeys']();
}

export function SetHotKeys(arg1) {
  return window['go']['app']['HotKeys']['SetHotKeys'](arg1);
}
