// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function DeleteProfile(arg1:string):Promise<void>;

export function ExportProfile(arg1:string):Promise<void>;

export function GetState():Promise<app.LibraryState>;

export function ImportProfile():Promise<void>;

export function OpenProfileFolder(arg1:string):Promise<void>;
