// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteProfile(arg1) {
  return window['go']['app']['Library']['DeleteProfile'](arg1);
}

export function ExportProfile(arg1) {
  return window['go']['app']['Library']['ExportProfile'](arg1);
}

export function GetState() {
  return window['go']['app']['Library']['GetState']();
}

export function ImportProfile() {
  return window['go']['app']['Library']['ImportProfile']();
}

export function OpenProfileFolder(arg1) {
  return window['go']['app']['Library']['OpenProfileFolder'](arg1);
}
