// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMonitors() {
  return window['go']['app']['OSKHelperBinding']['GetMonitors']();
}

export function GetState() {
  return window['go']['app']['OSKHelperBinding']['GetState']();
}

export function SetConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['app']['OSKHelperBinding']['SetConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function SetEnabled(arg1) {
  return window['go']['app']['OSKHelperBinding']['SetEnabled'](arg1);
}
