// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function GetState():Promise<app.OSKHelperState>;

export function SetConfig(arg1:number,arg2:string,arg3:string,arg4:number,arg5:number,arg6:string,arg7:number,arg8:number):Promise<void>;

export function SetEnabled(arg1:boolean):Promise<void>;
