// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function BrowseForDirectory():Promise<app.DirectorySelection>;

export function BuildKeyboardProfile(arg1:app.KeyboardBuildRequest):Promise<void>;

export function BuildMouseProfile(arg1:app.MouseBuildRequest):Promise<void>;

export function RefreshAudioFiles(arg1:string):Promise<Array<app.AudioFile>>;
