// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseForDirectory() {
  return window['go']['app']['ProfileBuilder']['BrowseForDirectory']();
}

export function BuildKeyboardProfile(arg1) {
  return window['go']['app']['ProfileBuilder']['BuildKeyboardProfile'](arg1);
}

export function BuildMouseProfile(arg1) {
  return window['go']['app']['ProfileBuilder']['BuildMouseProfile'](arg1);
}

export function RefreshAudioFiles(arg1) {
  return window['go']['app']['ProfileBuilder']['RefreshAudioFiles'](arg1);
}
