// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {rules} from '../models';
import {app} from '../models';

export function ClearDefaultKeyboardProfile():Promise<void>;

export function ClearDefaultMouseProfile():Promise<void>;

export function Disable():Promise<void>;

export function Enable():Promise<void>;

export function GetDefaultProfiles():Promise<rules.Profiles>;

export function GetKeyboardProfiles():Promise<Array<string>>;

export function GetKeyboardVolume():Promise<number>;

export function GetMouseProfiles():Promise<Array<string>>;

export function GetMouseVolume():Promise<number>;

export function GetState():Promise<app.StatusPanelState>;

export function IsEnabled():Promise<boolean>;

export function MuteKeyboard():Promise<void>;

export function MuteMouse():Promise<void>;

export function SetDefaultKeyboardProfile(arg1:string):Promise<void>;

export function SetDefaultMouseProfile(arg1:string):Promise<void>;

export function SetDefaultProfiles(arg1:any,arg2:any):Promise<void>;

export function SetKeyboardVolume(arg1:number):Promise<void>;

export function SetMouseVolume(arg1:number):Promise<void>;

export function ToggleMuteKeyboard():Promise<void>;

export function ToggleMuteMouse():Promise<void>;

export function UnmuteKeyboard():Promise<void>;

export function UnmuteMouse():Promise<void>;
