// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearDefaultKeyboardProfile() {
  return window['go']['app']['StatusPanel']['ClearDefaultKeyboardProfile']();
}

export function ClearDefaultMouseProfile() {
  return window['go']['app']['StatusPanel']['ClearDefaultMouseProfile']();
}

export function Disable() {
  return window['go']['app']['StatusPanel']['Disable']();
}

export function Enable() {
  return window['go']['app']['StatusPanel']['Enable']();
}

export function GetDefaultProfiles() {
  return window['go']['app']['StatusPanel']['GetDefaultProfiles']();
}

export function GetKeyboardProfiles() {
  return window['go']['app']['StatusPanel']['GetKeyboardProfiles']();
}

export function GetKeyboardVolume() {
  return window['go']['app']['StatusPanel']['GetKeyboardVolume']();
}

export function GetMouseProfiles() {
  return window['go']['app']['StatusPanel']['GetMouseProfiles']();
}

export function GetMouseVolume() {
  return window['go']['app']['StatusPanel']['GetMouseVolume']();
}

export function GetState() {
  return window['go']['app']['StatusPanel']['GetState']();
}

export function IsEnabled() {
  return window['go']['app']['StatusPanel']['IsEnabled']();
}

export function MuteKeyboard() {
  return window['go']['app']['StatusPanel']['MuteKeyboard']();
}

export function MuteMouse() {
  return window['go']['app']['StatusPanel']['MuteMouse']();
}

export function SetDefaultKeyboardProfile(arg1) {
  return window['go']['app']['StatusPanel']['SetDefaultKeyboardProfile'](arg1);
}

export function SetDefaultMouseProfile(arg1) {
  return window['go']['app']['StatusPanel']['SetDefaultMouseProfile'](arg1);
}

export function SetDefaultProfiles(arg1, arg2) {
  return window['go']['app']['StatusPanel']['SetDefaultProfiles'](arg1, arg2);
}

export function SetKeyboardVolume(arg1) {
  return window['go']['app']['StatusPanel']['SetKeyboardVolume'](arg1);
}

export function SetMouseVolume(arg1) {
  return window['go']['app']['StatusPanel']['SetMouseVolume'](arg1);
}

export function ToggleMuteKeyboard() {
  return window['go']['app']['StatusPanel']['ToggleMuteKeyboard']();
}

export function ToggleMuteMouse() {
  return window['go']['app']['StatusPanel']['ToggleMuteMouse']();
}

export function UnmuteKeyboard() {
  return window['go']['app']['StatusPanel']['UnmuteKeyboard']();
}

export function UnmuteMouse() {
  return window['go']['app']['StatusPanel']['UnmuteMouse']();
}
