// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAnalyticsID() {
  return window['go']['main']['App']['GetAnalyticsID']();
}

export function GetAnalyticsLastPingTimeMS() {
  return window['go']['main']['App']['GetAnalyticsLastPingTimeMS']();
}

export function GetStartWithSystem() {
  return window['go']['main']['App']['GetStartWithSystem']();
}

export function SetStartWithSystem(arg1) {
  return window['go']['main']['App']['SetStartWithSystem'](arg1);
}

export function UpdateAnalyticsLastPingTime() {
  return window['go']['main']['App']['UpdateAnalyticsLastPingTime']();
}
