// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStartWithSystem() {
  return window['go']['main']['App']['GetStartWithSystem']();
}

export function SetStartWithSystem(arg1) {
  return window['go']['main']['App']['SetStartWithSystem'](arg1);
}
