// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAnalyticsID():Promise<string>;

export function GetAnalyticsLastPingTimeMS():Promise<number>;

export function GetStartWithSystem():Promise<boolean>;

export function SetStartWithSystem(arg1:boolean):Promise<void>;

export function UpdateAnalyticsLastPingTime():Promise<void>;
