// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate():Promise<void>;

export function CheckForUpdateAndNotify():Promise<void>;

export function GetDownloadURL():Promise<string>;

export function GetLatestVersion():Promise<string>;

export function IsUpdateAvailable():Promise<boolean>;
