// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['UpdateDetails']['CheckForUpdate']();
}

export function CheckForUpdateAndNotify() {
  return window['go']['main']['UpdateDetails']['CheckForUpdateAndNotify']();
}

export function GetDownloadURL() {
  return window['go']['main']['UpdateDetails']['GetDownloadURL']();
}

export function GetLatestVersion() {
  return window['go']['main']['UpdateDetails']['GetLatestVersion']();
}

export function IsUpdateAvailable() {
  return window['go']['main']['UpdateDetails']['IsUpdateAvailable']();
}
